name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install npm dependencies
        run: npm install
      # - name: Run build task
      #   run: npm run build --if-present
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PASS }}
          # ARGS: "-rltgoDzvO --delete"
          # SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: "/home/deployer/deploy-nodejs/" # ${{ secrets.REMOTE_TARGET }}
      # - name: Connection on server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     key: ${{ secrets.SSH_KEY }}
      #     passphrase: ${{ secrets.SSH_PASS }}
      #     username: ${{ secrets.SSH_USER }}
      #     port: 22
      #     script: |
      #       cd deploy-nodejs
      #       ${{ secrets.REPO_PULL }}
      #       npm install
      #       pm2 start 0
