name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connection on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          username: ${{ secrets.SSH_USER }}
          port: 22
          script: |
            cd deploy-nodejs
            ${{ secrets.REPO_PULL }}
            npm install
            pm2 start 0
